bionic_university_student_homepage:
    pattern:  /
    defaults: { _controller: BionicUniversityStudentBundle:Default:index }

bionic_university_student_bundle_university:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing/university.yml"
    prefix:   /university

bionic_university_student_bundle_faculty:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing/faculty.yml"
    prefix:   /faculty

bionic_university_student_bundle_cafedra:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing/cafedra.yml"
    prefix:   /cafedra

bionic_university_student_bundle_student:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing/student.yml"
    prefix:   /student