bionic_university_final_project:
    resource: "@BionicUniversityFinalProjectBundle/Resources/config/routing.yml"
    prefix:   /main

bionic_university_student:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing.yml"
    prefix:   /

