bionic_university_user:
    resource: "@BionicUniversityUserBundle/Resources/config/routing.yml"
    prefix:   /user

bionic_university_student:
    resource: "@BionicUniversityStudentBundle/Resources/config/routing.yml"
    prefix:   /

