security:
    hide_user_not_found: false
    encoders:
        BionicUniversity\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 5000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user:
            entity:
                class:              BionicUniversity\UserBundle\Entity\User
                property:           email
                manager_name:       ~

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/user
            anonymous: ~
            form_login:
                login_path:  /user/login
                check_path:  /user/login_check
                username_parameter: _email
                password_parameter: _password
                always_use_default_target_path: true
                default_target_path: /user

            logout:
                path:   /user/logout
                target: /user

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }
