<?php

namespace BionicUniversity\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscribesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscribesRepository extends EntityRepository
{
}
