<?php

namespace BionicUniversity\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserGORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGoRepository extends EntityRepository
{
}
