bionic_university_user_homepage:
    pattern:  /
    defaults: { _controller: BionicUniversityUserBundle:User:index }
bionic_university_user_register:
    pattern:  /register
    defaults: { _controller: BionicUniversityUserBundle:UsersRegistration:register }
bionic_university_user_login:
  pattern:   /login
  defaults:  { _controller: BionicUniversityUserBundle:Login:login }
login_check:
  pattern:   /login_check
bionic_university_user_logout:
  pattern: /logout

admin_panel:
  pattern:   /admin
  defaults: { _controller: BionicUniversityUserBundle:Admin:admin }
write_post:
  pattern:   /post
  defaults: { _controller: BionicUniversityUserBundle:User:post }
all_post:
  pattern:   /all_post
  defaults: { _controller: BionicUniversityUserBundle:User:show }

post_show:
    pattern:  /show/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:showPost" }

post_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:edit" }
my_post:
    pattern:  /my_post
    defaults: { _controller: "BionicUniversityUserBundle:User:myPost" }

post_update:
    pattern:  /update/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:update" }
    requirements: { _method: post|put }

post_delete:
    pattern:  /delete/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:delete" }
    requirements: { _method: post|delete }

post_moderate:
    pattern:  /moderate
    defaults: { _controller: "BionicUniversityUserBundle:User:showModerate" }
post_push:
    pattern:  /moderate/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:moderate" }
user_go:
    pattern:  /show/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:userGo" }
user_subscribe:
    pattern:  /show/{id}
    defaults: { _controller: "BionicUniversityUserBundle:User:subscribe" }


