parameters:
#    bionic_university_final_project.example.class: BionicUniversity\FinalProjectBundle\Example

services:
#    bionic_university_final_project.example:
#        class: %bionic_university_final_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
